spring:
  datasource:
    driverClassName: org.postgresql.Driver
#    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME:mbm3}?useSSL=false
#    url: jdbc:mysql://localhost:6603/mbm_v1?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      initialization-fail-timeout: 0
  sql:
    init:
      mode: always
  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: false
  mvc:
    format:
      date: yyyy-MM-dd
      time: HH:mm
      date-time: yyyy-MM-dd HH:mm
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


#Cloudinary Properties
cloudinary:
  api-key: 299495348844489
  api-secret: ${CLOUDINARY_SECRET}
  cloud-name: tdimitrov
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
